name: LegendaryGuild
main: com.legendaryrealms.LegendaryGuild.LegendaryGuild
version: 5.2.0
api-version: 1.21
folia-supported: true
depend:
  - Vault
  - PlaceholderAPI
  - ProtocolLib
softdepend:
  - PlayerPoints
  - AttributePlus
  - SX-Attribute
  - MythicLib
commands:
  legendaryguild:
    description: "LegendaryGuild main command"
    usage: "/<command> [subcommand]"
    # 基础别名（更多别名可在config.yml中配置）
    # Basic aliases (more aliases can be configured in config.yml)
    aliases:
      - guild